### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by SnowySchoko** [staifa/php_bandwidth_hero_proxy#10]
I got everything running in truenas scale, even the test image works.
But now the main site (localhost:9696) is simply white, without the bandwith hero writing on the top left, and the addon does not recognize the site as a proxy.

If needed, I can provide a log.

**Comment by staifa** [comment]
Yes, providing log will help. Also, it currently works correctly only in firefox, I'm deploying fix for chrome in coming days.

**Comment by SnowySchoko** [comment]
This is what the log looks like after the service has been started and the test image has been opened.
Despite the last line stating that the service will be closed, the Docker container is still running.
When I try to enter the URL in the URL field of the compression service, the log doesn't change further.

The log as promised:

2024-11-17 09:35:29.433392-08:00[Sun Nov 17 17:35:29 2024] PHP 8.3.13 Development Server (http://0.0.0.0:8000) started
2024-11-17 09:36:37.241052-08:00[Sun Nov 17 17:36:37 2024] 192.168.178.43:6091 Accepted
2024-11-17 09:36:37.283607-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "BHERO_LOGIN" in /usr/src/app/config.php on line 24
2024-11-17 09:36:37.283707-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "BHERO_PASSWORD" in /usr/src/app/config.php on line 25
2024-11-17 09:36:37.283771-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "jpeg" in /usr/src/app/config.php on line 31
2024-11-17 09:36:37.283870-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined variable $greyscale in /usr/src/app/config.php on line 48
2024-11-17 09:36:37.286757-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "PHP_AUTH_USER" in /usr/src/app/auth.php on line 12
2024-11-17 09:36:37.286839-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "PHP_AUTH_PW" in /usr/src/app/auth.php on line 13
2024-11-17 09:36:37.286929-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "PHP_AUTH_USER" in /usr/src/app/auth.php on line 14
2024-11-17 09:36:37.286967-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "PHP_AUTH_PW" in /usr/src/app/auth.php on line 14
2024-11-17 09:36:37.287008-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "HTTP_X_FORWARDED_FOR" in /usr/src/app/proxy.php on line 19
2024-11-17 09:36:37.287082-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "HTTP_COOKIE" in /usr/src/app/proxy.php on line 20
2024-11-17 09:36:37.287169-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "HTTP_REFERER" in /usr/src/app/proxy.php on line 22
2024-11-17 09:36:37.514911-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "http" in /usr/src/app/middleware/cleanup.php on line 12
2024-11-17 09:36:37.515005-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "image" in /usr/src/app/middleware/cleanup.php on line 15
2024-11-17 09:36:37.515072-08:00[Sun Nov 17 17:36:37 2024] 192.168.178.43:6091 Closing
2024-11-17 09:36:37.629280-08:00[Sun Nov 17 17:36:37 2024] 192.168.178.43:6092 Accepted
2024-11-17 09:36:37.632721-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "BHERO_LOGIN" in /usr/src/app/config.php on line 24
2024-11-17 09:36:37.632835-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "BHERO_PASSWORD" in /usr/src/app/config.php on line 25
2024-11-17 09:36:37.632872-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "url" in /usr/src/app/config.php on line 28
2024-11-17 09:36:37.632985-08:00[Sun Nov 17 17:36:37 2024] PHP Deprecated:  urldecode(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/src/app/config.php on line 28
2024-11-17 09:36:37.633045-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "jpeg" in /usr/src/app/config.php on line 31
2024-11-17 09:36:37.633074-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined variable $greyscale in /usr/src/app/config.php on line 48
2024-11-17 09:36:37.633134-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "PHP_AUTH_USER" in /usr/src/app/auth.php on line 12
2024-11-17 09:36:37.633180-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "PHP_AUTH_PW" in /usr/src/app/auth.php on line 13
2024-11-17 09:36:37.633207-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "PHP_AUTH_USER" in /usr/src/app/auth.php on line 14
2024-11-17 09:36:37.633234-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "PHP_AUTH_PW" in /usr/src/app/auth.php on line 14
2024-11-17 09:36:37.633287-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined variable $http_response_code in /usr/src/app/router.php on line 15
2024-11-17 09:36:37.633664-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "http" in /usr/src/app/middleware/cleanup.php on line 12
2024-11-17 09:36:37.633722-08:00[Sun Nov 17 17:36:37 2024] PHP Warning:  Undefined array key "image" in /usr/src/app/middleware/cleanup.php on line 15
2024-11-17 09:36:37.633752-08:00[Sun Nov 17 17:36:37 2024] PHP Fatal error:  Uncaught Error: Value of type null is not callable in /usr/src/app/router.php:15
2024-11-17 09:36:37.633795-08:00Stack trace:
2024-11-17 09:36:37.633824-08:00#0 [internal function]: staifa\php_bandwidth_hero_proxy\router\{closure}(Array)
2024-11-17 09:36:37.633850-08:00#1 /usr/src/app/util.php(17): call_user_func(Object(Closure), Array)
2024-11-17 09:36:37.633876-08:00#2 /usr/src/app/main.php(38): staifa\php_bandwidth_hero_proxy\util\flow(Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure), Object(Closure))
2024-11-17 09:36:37.633915-08:00#3 /usr/src/app/middleware/cleanup.php(10): staifa\php_bandwidth_hero_proxy\main\{closure}(Array)
2024-11-17 09:36:37.633943-08:00#4 /usr/src/app/middleware/context_logger.php(10): staifa\php_bandwidth_hero_proxy\middleware\cleanup\{closure}(Array)
2024-11-17 09:36:37.633969-08:00#5 /usr/src/app/main.php(47): staifa\php_bandwidth_hero_proxy\middleware\context_logger\{closure}(Array)
2024-11-17 09:36:37.634099-08:00#6 /usr/src/app/index.php(36): staifa\php_bandwidth_hero_proxy\main\run(Object(Closure))
2024-11-17 09:36:37.634138-08:00#7 {main}
2024-11-17 09:36:37.634166-08:00thrown in /usr/src/app/router.php on line 15
2024-11-17 09:36:37.634819-08:00[Sun Nov 17 17:36:37 2024] 192.168.178.43:6092 Closing

**Comment by staifa** [comment]
Thank you for the log. The last line states that current request processing is closed, not the service itself. The problem could be in communication between the browser extension and the docker, I had to add specific routing for it to work on my local. I will investigate, can you provide whole request, response, browser and os you are using so I can replicate the problem locally please?

**Comment by SnowySchoko** [comment]
Unfortunately, I don't know what you mean with whole request and response, but I use Google Chrome (131.0.6778.70 (64-Bit)) and Windows 11 (Build 22631.4460).
I have also tried another fork of Bandwidth Hero (rusty-bandwith), which is a locally running Rust port.
I was able to add his URL to the addon, and it did work, so the addon should still work.

**Comment by staifa** [comment]
This is now fixed as far as I can tell.

**Comment by staifa** [comment]
This should be fixed now, can you verify @SnowySchoko please?
